# This file enables the Travis continuous integration system, which
# automatically builds and tests the project for each GitHub commit or
# pull request on three separate JDKs.
#
# For more information, see https://travis-ci.org

sudo: true

language: scala

jdk:
  - oraclejdk8
  # - oraclejdk9 Let's assume 8 and 10 is enough
  - oraclejdk10

scala:
  - 2.10.7
  - 2.11.12
  - 2.12.7
  - 2.13.0-M5

before_install:
  - export PATH=${PATH}:./vendor/bundle

env:
  - TRAVIS_NODE_VERSION="8.11.4"
  - TRAVIS_NODE_VERSION="9.11.2"
  - TRAVIS_NODE_VERSION="10.9.0"

install:
  - rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install $TRAVIS_NODE_VERSION
  - npm install
  - rvm use 2.3.3 --install --fuzzy
  - gem update --system
  - gem install sass
  - gem install jekyll -v 3.6.2

cache:
  directories:
    - $HOME/.ivy2
    - $HOME/.m2
    - $HOME/.coursier
    - $HOME/.sbt/boot

script:
  - sudo chmod +x /usr/local/bin/sbt
  - sbt ++$TRAVIS_SCALA_VERSION -J-Xmx4G clean scalajavatimeJVM/compile scalajavatimeTestsJVM/compile
  - if [[ $TRAVIS_SCALA_VERSION != "2.13.0-M5" ]]; then sbt ++$TRAVIS_SCALA_VERSION -J-Xmx4G clean scalajavatimeTestsJVM/test scalajavatimeTestsJS/test scalajavatimeJVM/publishLocal scalajavatimeJS/publishLocal scalajavatimeTZDBJVM/publishLocal scalajavatimeTZDBJS/publishLocal; fi;
  # docs/makeMicrosite
  # Tricks to avoid unnecessary cache updates, from
  # http://www.scala-sbt.org/0.13/docs/Travis-CI-with-sbt.html
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
